spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080

logging:
  level:
    ru.borodinsemyon: WARN